-- Snowflake Database Setup for Comments App
-- Run these commands in your Snowflake environment

-- Create database and schema
CREATE DATABASE IF NOT EXISTS TABLEAU_EXTENSIONS;
USE DATABASE TABLEAU_EXTENSIONS;
CREATE SCHEMA IF NOT EXISTS COMMENTS_APP;
USE SCHEMA COMMENTS_APP;

-- Create posts table with rich text support
CREATE OR REPLACE TABLE POSTS (
    ID VARCHAR(50) PRIMARY KEY,
    POST_TYPE VARCHAR(100) NOT NULL,
    METRIC_VALUE VARCHAR(200) NOT NULL,
    METRIC_LABEL VARCHAR(200) NOT NULL,
    CONTENT TEXT NOT NULL,  -- Stores HTML/rich text content
    AUTHOR VARCHAR(100) DEFAULT 'Current User',
    TIMESTAMP_MS BIGINT NOT NULL,
    LIKES INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create comments table
CREATE OR REPLACE TABLE COMMENTS (
    ID VARCHAR(50) PRIMARY KEY,
    POST_ID VARCHAR(50) NOT NULL,
    AUTHOR VARCHAR(100) DEFAULT 'Current User',
    CONTENT TEXT NOT NULL,  -- Plain text for comments
    TIMESTAMP_MS BIGINT NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (POST_ID) REFERENCES POSTS(ID)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS IDX_POSTS_TIMESTAMP ON POSTS(TIMESTAMP_MS);
CREATE INDEX IF NOT EXISTS IDX_COMMENTS_POST_ID ON COMMENTS(POST_ID);
CREATE INDEX IF NOT EXISTS IDX_COMMENTS_TIMESTAMP ON COMMENTS(TIMESTAMP_MS);

-- Create a view that joins posts with comment counts
CREATE OR REPLACE VIEW POSTS_WITH_COMMENTS AS
SELECT
    p.*,
    COALESCE(c.COMMENT_COUNT, 0) as COMMENT_COUNT
FROM POSTS p
LEFT JOIN (
    SELECT
        POST_ID,
        COUNT(*) as COMMENT_COUNT
    FROM COMMENTS
    GROUP BY POST_ID
) c ON p.ID = c.POST_ID
ORDER BY p.TIMESTAMP_MS DESC;

-- Grant permissions (adjust role as needed)
-- GRANT ALL PRIVILEGES ON SCHEMA COMMENTS_APP TO ROLE YOUR_ROLE;
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA COMMENTS_APP TO ROLE YOUR_ROLE;

-- Sample data insertion (optional)
-- INSERT INTO POSTS (ID, POST_TYPE, METRIC_VALUE, METRIC_LABEL, CONTENT, TIMESTAMP_MS)
-- VALUES ('sample-1', 'Monthly Review', '$2.4M (+12%)', 'November Revenue',
--         '<p>Great performance this month! <span style="color: red;">Revenue exceeded</span> expectations.</p>',
--         EXTRACT(EPOCH FROM CURRENT_TIMESTAMP()) * 1000);

SELECT 'Snowflake setup completed successfully!' as STATUS;